#!/usr/bin/env python3
"""Run every compiled-in decoder over the shared probe cases and compare
byte-for-byte against the ffmpeg rawvideo references generated by probe.py.

Does NOT regenerate inputs or references — the point is identical inputs
across candidates. Missing refs/cases are reported as "missing", not skipped.

Usage: compare_all.py [--iterations N] [--decoders a,b,c]
Exit 0 iff every decoder×case pair is "exact" (or "unsupported" when the
adapter reports a clean FeatureNotSupported-style error — see notes).
"""
import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
RESULTS = ROOT / "results"
HARNESS = "/tmp/zenmedia-resume-20260928/candidates/target/release/h264-harness"

DECODERS = ["rust_h264", "rusty_h264", "hibernia", "oxideav", "wedeo"]


def load_cases() -> list[str]:
    """Case order from the manifest; falls back to the probe's nine."""
    m = RESULTS / "cases.json"
    if m.exists():
        return [c["name"] for c in json.loads(m.read_text())["cases"]
                if c["status"] == "ok"]
    return ["baseline", "main_b", "high_b", "high_multi_slice", "cropped",
            "open_gop", "360p", "mbaff", "high10"]


def sha256(p: Path) -> str:
    import hashlib
    return hashlib.sha256(p.read_bytes()).hexdigest()


def main() -> int:
    iters = 1
    decoders = DECODERS
    args = sys.argv[1:]
    if "--iterations" in args:
        i = args.index("--iterations")
        iters = int(args[i + 1])
    if "--decoders" in args:
        i = args.index("--decoders")
        decoders = args[i + 1].split(",")

    cases = load_cases()
    report = {"harness": HARNESS, "cases": []}
    worst = 0
    for dec in decoders:
        for case in cases:
            inp = RESULTS / f"{case}.h264"
            ref = RESULTS / f"{case}.ref.yuv"
            got = RESULTS / f"{case}.{dec}.got.yuv"
            rec = {"decoder": dec, "case": case}
            if not inp.exists() or not ref.exists():
                rec["status"] = "missing"
                report["cases"].append(rec)
                worst = max(worst, 1)
                continue
            try:
                proc = subprocess.run(
                    [HARNESS, dec, str(inp), str(got), str(iters)],
                    capture_output=True, text=True, timeout=300,
                )
            except subprocess.TimeoutExpired:
                rec["status"] = "timeout"
                report["cases"].append(rec)
                worst = max(worst, 1)
                continue
            rec["exit_code"] = proc.returncode
            lines = [l for l in proc.stdout.splitlines() if l.strip().startswith("{")]
            if lines:
                rec["output"] = json.loads(lines[0])
            if proc.returncode != 0:
                err = proc.stderr
                if "panicked at" in err or proc.returncode < 0 or proc.returncode > 128:
                    rec["status"] = "crash"
                elif "FeatureNotSupported" in err or "Unsupported(" in err:
                    rec["status"] = "rejected"
                else:
                    rec["status"] = "error"
                rec["stderr"] = proc.stderr[-2000:]
                report["cases"].append(rec)
                worst = max(worst, 1)
                continue
            if not got.exists():
                rec["status"] = "error"
                rec["stderr"] = proc.stderr[-2000:]
                report["cases"].append(rec)
                worst = max(worst, 1)
                continue
            rb, gb = ref.read_bytes(), got.read_bytes()
            rec["reference_bytes"] = len(rb)
            rec["actual_bytes"] = len(gb)
            rec["reference_sha256"] = sha256(ref)
            rec["got_sha256"] = sha256(got)
            out = rec.get("output") or {}
            if out.get("geometry_changes", 0) > 0:
                # Mixed-geometry stream: the flat rawvideo reference can't
                # express per-frame size changes (ffmpeg emits first-SPS
                # geometry throughout). Verdict = decoder reinit handling.
                rec["status"] = "reinit_ok" if len(gb) > len(rb) else "reinit_wrong"
            elif rb == gb:
                rec["status"] = "exact"
            else:
                n = sum(a != b for a, b in zip(rb, gb))
                n += abs(len(rb) - len(gb))
                rec["status"] = "mismatch"
                rec["differing_bytes"] = n
                worst = 1
            report["cases"].append(rec)

    out = RESULTS / "compare_report.json"
    out.write_text(json.dumps(report, indent=2))
    # console matrix
    by = {}
    for r in report["cases"]:
        by.setdefault(r["case"], {})[r["decoder"]] = (
            "exact" if r["status"] == "exact"
            else f"{r['status']}:{r.get('differing_bytes', '')}"
        )
    hdr = ["case"] + decoders
    print(("{:<18}" * len(hdr)).format(*hdr))
    for case in cases:
        row = [case] + [by.get(case, {}).get(d, "-") for d in decoders]
        print(("{:<18}" * len(row)).format(*row))
    print(f"report: {out}")
    return worst


if __name__ == "__main__":
    sys.exit(main())
